packages:
  - client
  - server
  - bun-server

catalog:
  '@types/node': 22.20.1
  typescript: 7.0.2

allowBuilds:
  argon2: true
  esbuild: false

minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'
