const MAX_AUTO_TITLE_LENGTH = 18
const MAX_CONVERSATION_TITLE_LENGTH = 200
const MAX_SEARCH_QUERY_LENGTH = 500
const MAX_QUESTION_LENGTH = 100_000
const MAX_IMPORT_CONVERSATIONS = 2_000
const MAX_MESSAGES_PER_CONVERSATION = 20_000

export {
  MAX_AUTO_TITLE_LENGTH,
  MAX_CONVERSATION_TITLE_LENGTH,
  MAX_IMPORT_CONVERSATIONS,
  MAX_MESSAGES_PER_CONVERSATION,
  MAX_QUESTION_LENGTH,
  MAX_SEARCH_QUERY_LENGTH,
}
