const MAX_AUTO_TITLE_LENGTH = 18
const MAX_CONVERSATION_TITLE_LENGTH = 200
const MAX_SEARCH_QUERY_LENGTH = 500
const MAX_QUESTION_LENGTH = 100_000
const MAX_IMPORT_CONVERSATIONS = 2_000
const MAX_MESSAGES_PER_CONVERSATION = 20_000
const MAX_STORED_TOOL_TRACE_ITEMS = 20
const MAX_STORED_TOOL_TRACE_SUMMARY_LENGTH = 240
const MAX_IMAGE_ATTACHMENT_BYTES = 6 * 1024 * 1024
const MAX_IMAGE_ATTACHMENTS_PER_MESSAGE = 4
const MAX_IMAGE_ATTACHMENT_EDGE = 4096
const MAX_PROVIDER_IMAGE_REQUEST_BYTES = 40 * 1024 * 1024
const MAX_PORTABLE_BACKUP_BYTES = 256 * 1024 * 1024
const DEFAULT_ATTACHMENT_ORPHAN_TTL_MS = 24 * 60 * 60 * 1000

export {
  MAX_AUTO_TITLE_LENGTH,
  MAX_CONVERSATION_TITLE_LENGTH,
  MAX_IMPORT_CONVERSATIONS,
  MAX_IMAGE_ATTACHMENT_BYTES,
  MAX_IMAGE_ATTACHMENT_EDGE,
  MAX_IMAGE_ATTACHMENTS_PER_MESSAGE,
  MAX_MESSAGES_PER_CONVERSATION,
  MAX_PORTABLE_BACKUP_BYTES,
  MAX_PROVIDER_IMAGE_REQUEST_BYTES,
  MAX_QUESTION_LENGTH,
  MAX_SEARCH_QUERY_LENGTH,
  MAX_STORED_TOOL_TRACE_ITEMS,
  MAX_STORED_TOOL_TRACE_SUMMARY_LENGTH,
  DEFAULT_ATTACHMENT_ORPHAN_TTL_MS,
}
